version: "3"
services:
  todoapp:
    build: .
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@postgres:5432/fastapi
    ports:
      - "5000:80"
    depends_on:
      - postgres
  
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fastapi
    volumes:
      - postgres-data:/var/lib/postgrsql/data
    expose:
      - 5432
    
volumes:
  postgres-data: