"""added task model

Revision ID: b025cbe46059
Revises: 
Create Date: 2023-09-21 16:26:04.109283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.config.database import GUID

# revision identifiers, used by Alembic.
revision: str = 'b025cbe46059'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DONE', 'PENDING', 'CANCELLED', name='statusvalue'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
